# Generated by Django 4.2.3 on 2023-07-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cuisine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.cuisine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
