# Generated by Django 4.2.3 on 2023-07-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_category_menuitem_cuisine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'managed': False},
        ),
    ]
