# Generated by Django 4.2.3 on 2023-07-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menuitem',
            table='menu_menuitem',
        ),
    ]
