# Generated by Django 4.2.3 on 2023-07-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
    ]
