# Generated by Django 4.2.3 on 2023-07-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(to='menu.ingredient'),
        ),
    ]
